#!/usr/bin/env bash
set -euo pipefail

# Read exact wasm-bindgen version pinned in Cargo.lock
REQUIRED=$(awk '/^name = "wasm-bindgen"$/{found=1} found && /^version/{gsub(/"/, "", $3); print $3; exit}' Cargo.lock)
INSTALLED=$(wasm-bindgen --version 2>/dev/null | awk '{print $2}' || true)

if [ "$INSTALLED" != "$REQUIRED" ]; then
  echo "wasm-bindgen-cli $INSTALLED != $REQUIRED — installing $REQUIRED"
  if command -v cargo-binstall &>/dev/null; then
    cargo binstall "wasm-bindgen-cli@$REQUIRED" --no-confirm
  else
    cargo install wasm-bindgen-cli --version "$REQUIRED" --locked
  fi
fi

cargo build --release --target wasm32-unknown-unknown
wasm-bindgen --target bundler --out-dir ../src/wasm target/wasm32-unknown-unknown/release/inflate_wasm.wasm
rm -f ../src/wasm/inflate_wasm_bg.wasm.d.ts

# wasm-bindgen emits `getStringFromWasm0` as a TextDecoder.decode over a
# subarray of WebAssembly.Memory. That buffer is a RESIZABLE ArrayBuffer, and
# TextDecoder.decode rejects views over resizable buffers in browsers, so every
# string leaving Rust throws — and since the only strings this crate returns are
# error messages, the module cannot report its own errors: consumers see
# "TypeError: ... must not be resizable" in place of the real cause. The Vec<u8>
# path is unaffected because wasm-bindgen already emits `.slice()` there.
#
# Copy before decoding. Patched here rather than in src/wasm by hand, because
# that directory is regenerated by the command above and an edit there is lost
# on the next build. Idempotent, and fails loudly if the upstream shape changes.
# Rationale in full: bgzf-filehandle agent-docs/adr/0002.
glue=../src/wasm/inflate_wasm_bg.js
decode='return cachedTextDecoder.decode(getUint8ArrayMemory0().subarray(ptr, ptr + len));'
if grep -qF "$decode" "$glue"; then
  perl -pi -e 's/\Qsubarray(ptr, ptr + len)\E\);$/subarray(ptr, ptr + len).slice());/' "$glue"
  grep -qF '.slice());' "$glue" || { echo "string-decode patch did not apply to $glue" >&2; exit 1; }
  echo "patched getStringFromWasm0 to copy out of wasm memory"
elif grep -qF '.slice());' "$glue"; then
  echo "getStringFromWasm0 already copies"
else
  echo "wasm-bindgen changed getStringFromWasm0; re-check the resizable-buffer patch" >&2
  exit 1
fi
